# Generated by Django 2.1.7 on 2020-06-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HL7_MESSAGE_LOGS',
            fields=[
                ('MESSAGE_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='消息ID')),
                ('MESSAGE_BODY', models.CharField(blank=True, default='', max_length=100, verbose_name='消息主体')),
                ('CREATE_USER', models.CharField(blank=True, default='', max_length=100, verbose_name='创建人')),
                ('CREATE_DATE', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
            options={
                'ordering': ('MESSAGE_ID',),
            },
        ),
        migrations.CreateModel(
            name='JHINIS_CARE_MAIN',
            fields=[
                ('CARE_MAIN_INDEX', models.AutoField(primary_key=True, serialize=False, verbose_name='护理主索引')),
                ('APPLY_ID', models.IntegerField(default=0, verbose_name='该患者是否已经归档')),
                ('PATIENT_ID', models.CharField(blank=True, default='', max_length=100, verbose_name='病案号')),
                ('VISIT_ID', models.IntegerField(default=0, verbose_name='患者住院次')),
                ('INP_NO', models.CharField(blank=True, default='', max_length=100, verbose_name='住院号')),
                ('HOSPITAL_NO', models.CharField(blank=True, default='', max_length=100, verbose_name='医院编码')),
                ('BED_ID', models.IntegerField(default=-1, verbose_name='床位ID')),
                ('CREATE_USER', models.CharField(blank=True, default='', max_length=100, verbose_name='创建人')),
                ('CREATE_DATE', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('IN_DEPT_DATE', models.DateTimeField(verbose_name='入科日期')),
                ('OUT_DEPT_DATE', models.DateTimeField(verbose_name='出科日期')),
                ('STATE', models.IntegerField(default=0, verbose_name='是否有效（0：有效 1：无效）')),
                ('DOCTOR', models.CharField(blank=True, default='', max_length=100, verbose_name='住院号')),
                ('DEPT_CODE', models.CharField(blank=True, default='', max_length=100, verbose_name='住院号')),
            ],
            options={
                'ordering': ('CARE_MAIN_INDEX',),
            },
        ),
    ]
